### ISSUE TITLE
Practica calidad

### ISSUE THREAD

**Issue by ThorSampy** [SistemasTecTlaxiaco/practica-de-calidad-entrevista-equipo-cb-24h#1]
[Practica calidad.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calidad-entrevista-equipo-cb-24h/files/7348442/Practica.calidad.pdf)

**Comment by CarlosSD16** [comment]
Calificación:18

**Comment by josealfredo79** [comment]
Falto el código a revisar para calcular la complejidad ciclomática
